export const PRODUCT_FILTERS = [
  { filter: '*', label: 'Todos' },
  { filter: '.filter-nike', label: 'Nike' },
  { filter: '.filter-adidas', label: 'Adidas' },
  { filter: '.filter-puma', label: 'Puma' },
  { filter: '.filter-vans', label: 'Vans' },
];

export const PRODUCTS = [
  {
    id: 1,
    name: 'Nike Air Max',
    price: 89990,
    oldPrice: 129990,
    rating: 4.5,
    reviews: 24,
    image: '/images/nike_air_max_plus.png',
    hoverImage: '/images/nike_air_Jordan_masculino.webp',
    brand: 'nike',
    isNew: false,
    isSale: true,
    category: 'filter-nike',
    colors: ['Preto', 'Branco', 'Azul'],
    colorValues: ['#1a1a1a', '#f5f5f5', '#2563eb']
  },
  {
    id: 2,
    name: 'Adidas Ultraboost',
    price: 79990,
    oldPrice: null,
    rating: 5,
    reviews: 18,
    image: '/images/adidas_ultraboost.png',
    hoverImage: '/images/adidas_nmd.webp',
    brand: 'adidas',
    isNew: true,
    isSale: false,
    category: 'filter-adidas',
    colors: ['Preto', 'Branco', 'Vermelho'],
    colorValues: ['#1a1a1a', '#f5f5f5', '#dc2626']
  },
  {
    id: 3,
    name: 'Puma Suede',
    price: 69990,
    oldPrice: null,
    rating: 4,
    reviews: 7,
    image: '/images/puma_suede_classic.webp',
    hoverImage: '/images/puma_cali_sport.png',
    brand: 'puma',
    isNew: false,
    isSale: false,
    category: 'filter-puma',
    colors: ['Azul Marinho', 'Cinza', 'Verde'],
    colorValues: ['#1e3a8a', '#6b7280', '#16a34a']
  },
  {
    id: 4,
    name: 'Vans Old Skool',
    price: 59990,
    oldPrice: 89990,
    rating: 5,
    reviews: 32,
    image: '/images/vans_old_skool.webp',
    hoverImage: '/images/vans_ultraRange.webp',
    brand: 'vans',
    isNew: false,
    isSale: true,
    category: 'filter-vans',
    colors: ['Preto/Branco', 'Preto', 'Branco'],
    colorValues: ['#1a1a1a', '#1a1a1a', '#f5f5f5']
  },
  {
    id: 5,
    name: 'Nike Dunk Low',
    price: 109990,
    oldPrice: 139990,
    rating: 4.5,
    reviews: 15,
    image: '/images/nike_air_Jordan_masculino.webp',
    hoverImage: '/images/nike_air_Max_femenino.webp',
    brand: 'nike',
    isNew: true,
    isSale: true,
    category: 'filter-nike',
    colors: ['Rosa', 'Azul Claro', 'Verde'],
    colorValues: ['#ec4899', '#3b82f6', '#22c55e']
  },
  {
    id: 6,
    name: 'Adidas Campus',
    price: 64990,
    oldPrice: null,
    rating: 4,
    reviews: 21,
    image: '/images/adidas_nmd.webp',
    hoverImage: '/images/adidas_ultraboost.png',
    brand: 'adidas',
    isNew: false,
    isSale: false,
    category: 'filter-adidas',
    colors: ['Marrom', 'Cinza', 'Preto'],
    colorValues: ['#78350f', '#6b7280', '#1a1a1a']
  },
  {
    id: 7,
    name: 'Puma RS-X',
    price: 74990,
    oldPrice: null,
    rating: 4.5,
    reviews: 11,
    image: '/images/puma_cali_sport.png',
    hoverImage: '/images/puma_suede_classic.webp',
    brand: 'puma',
    isNew: true,
    isSale: false,
    category: 'filter-puma',
    colors: ['Branco/Preto', 'Azul', 'Vermelho'],
    colorValues: ['#f5f5f5', '#3b82f6', '#dc2626']
  },
  {
    id: 8,
    name: 'Vans Slip-On',
    price: 49990,
    oldPrice: null,
    rating: 5,
    reviews: 29,
    image: '/images/vans_ultraRange.webp',
    hoverImage: '/images/vans_old_skool.webp',
    brand: 'vans',
    isNew: false,
    isSale: false,
    category: 'filter-vans',
    colors: ['Branco', 'Preto', 'Vermelho'],
    colorValues: ['#f5f5f5', '#1a1a1a', '#dc2626']
  }
];